fixed deployment crash due to npm chalk
ardium-pl/homepage pull request #11
Opened 2024-07-05 22:00 UTC by WolnyMikolaj

2024-07-05 22:26 UTC, joker876 commented
Nie wiem co zrobiłeś inaczej niż zawsze, ale folder `.angular/cache` powinien być w gitignore

2024-07-05 22:27 UTC, joker876 requested changes
.

2024-07-07 20:56 UTC, WolnyMikolaj commented
> Do poprawy gitignore

Czekaj, jest przecież:

![image](https://github.com/ardium-pl/homepage/assets/136742392/2dd07cc8-3fc8-480a-84e9-02b715a85387)

2024-07-07 22:22 UTC, joker876 commented
Prawdopodobnie trzeba dodać to samo do gitignore w głównym folderze, bo po zmianie ścieżki buildu tworzą się te pliki w innym miejscu

2024-07-09 08:49 UTC, joker876 commented
Jeszcze musisz usunąć pliki cache z brancha, bo one nie mogą się znaleźć w repo

2024-08-19 18:21 UTC, closed without merging